### ISSUE TITLE
Integration with Wildfly 10

### ISSUE THREAD

**Issue by domtoupin** [stagemonitor/stagemonitor#165] opened 2016-06-06 17:09 UTC
Hi,

I'm currently trying to integrate stagemonitor in our non-servlet application (EAR) running under Wildfly 10.0.0.Final. The EAR is composed of several EJBs remotely called using JNDI.

So far, here is what I have done:
- I created a new Singleton bean that call `Stagemonitor.init()` in a method annotated with `@PostConstruct` and `Stagemonitor.shutDown()` in a method annotated with `@PreDestroy`
- I added a `stagemonitor.properties` file to one of my EJBs with the following content:
```
stagemonitor.applicationName=MyEJB
stagemonitor.instanceName=MyEJB
stagemonitor.profiler.logCallStacks=true
stagemonitor.elasticsearch.url=http://[my es url]:9200/
stagemonitor.instrument.include=com.mymodule
stagemonitor.instrument.jdbc.dataSource.implementations=org.apache.tomcat.jdbc.pool.DataSource, org.apache.tomcat.dbcp.dbcp.PoolingDataSource, org.apache.tomcat.jdbc.pool.DataSourceProxy, org.apache.commons.dbcp2.PoolingDataSource, org.apache.commons.dbcp.PoolingDataSource, com.mchange.v2.c3p0.AbstractPoolBackedDataSource, com.mchange.v2.c3p0.PoolBackedDataSource, com.mchange.v2.c3p0.ComboPooledDataSource, com.jolbox.bonecp.BoneCPDataSource, snaq.db.DBPoolDataSource, com.zaxxer.hikari.HikariDataSource, org.jboss.jca.adapters.jdbc.WrapperDataSource, org.springframework.jdbc.datasource.AbstractDriverBasedDataSource, org.jboss.as.connector.subsystems.datasources.WildFlyDataSource
```
- I also added the following Maven dependencies to my EAR pom.xml:
```
		<dependency>
			<groupId>org.stagemonitor</groupId>
			<artifactId>stagemonitor-requestmonitor</artifactId>
			<version>0.25.0</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.stagemonitor</groupId>
			<artifactId>stagemonitor-jdbc</artifactId>
			<version>0.25.0</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.stagemonitor</groupId>
			<artifactId>stagemonitor-jvm</artifactId>
			<version>0.25.0</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.stagemonitor</groupId>
			<artifactId>stagemonitor-os</artifactId>
			<version>0.25.0</version>
			<scope>runtime</scope>
		</dependency>
```

When I start my Wildfly server, I get the following messages related to stagemonitor:
```
INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-8) WFLYJCA0005: Deploying non-JDBC-compliant driver class org.stagemonitor.core.instrument.StagemonitorRuntimeAgentAttacherDriver (version 0.0)
INFO  [org.stagemonitor.core.Stagemonitor] (pool-9-thread-1) Measurement Session is initialized: [application=MyEJB] [instance=MyEJB] [host=some-host]
INFO  [org.stagemonitor.core.Stagemonitor] (pool-9-thread-1) Initializing plugin JvmPlugin
WARN  [org.stagemonitor.jvm.JvmPlugin] (pool-9-thread-1) Could not register cpu usage. (com.sun.management.OperatingSystemMXBean from [Module "deployment.bc360-server-ear-vanilla-9.0.0-SNAPSHOT.ear:main" from Service Module Loader])
INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-3) WFLYJCA0018: Started Driver service with driver-name = bc360-server-ear-vanilla-9.0.0-SNAPSHOT.ear_org.stagemonitor.core.instrument.StagemonitorRuntimeAgentAttacherDriver_0_0
INFO  [org.stagemonitor.core.Stagemonitor] (pool-9-thread-1) Initializing plugin JdbcPlugin
INFO  [org.stagemonitor.core.Stagemonitor] (pool-9-thread-1) Initializing plugin WebPlugin
INFO  [org.stagemonitor.core.Stagemonitor] (pool-9-thread-1) Initializing plugin OsPlugin
INFO  [org.stagemonitor.core.Stagemonitor] (pool-9-thread-1) Initializing plugin CorePlugin
INFO  [org.stagemonitor.core.CorePlugin] (pool-9-thread-1) Not sending metrics to InfluxDB (url=null, interval=60s)
WARN  [org.stagemonitor.core.util.HttpClient$ErrorLoggingResponseHandler] (async-elasticsearch) http://[my es url]:9200/stagemonitor: 400 {"error":{"root_cause":[{"type":"index_already_exists_exception","reason":"already exists","index":"stagemonitor"}],"type":"index_already_exists_exception","reason":"already exists","index":"stagemonitor"},"status":400}
INFO  [org.stagemonitor.core.CorePlugin] (pool-9-thread-1) Sending metrics to Elasticsearch ([http://[my es url]:9200/]) every 60s
INFO  [org.stagemonitor.core.Stagemonitor] (pool-9-thread-1) Initializing plugin RequestMonitorPlugin
INFO  [org.stagemonitor.core.elasticsearch.ElasticsearchClient] (elasticsearch-tasks) Deleting indices: http://[my es url]:9200/stagemonitor-requests-*,-stagemonitor-requests-2016.06.*,-stagemonitor-requests-2016.05.31,-stagemonitor-requests-2016.05.30?timeout=20m&ignore_unavailable=true
INFO  [org.stagemonitor.core.elasticsearch.ElasticsearchClient] (elasticsearch-tasks) Deleting indices: Done http://[my es url]:9200/stagemonitor-requests-*,-stagemonitor-requests-2016.06.*,-stagemonitor-requests-2016.05.31,-stagemonitor-requests-2016.05.30?timeout=20m&ignore_unavailable=true
INFO  [org.stagemonitor.web.configuration.ConfigurationServlet] (ServerService Thread Pool -- 94) Registering configuration Endpoint /stagemonitor/configuration. You can dynamically change the configuration by issuing a POST request to /stagemonitor/configuration?key=stagemonitor.config.key&value=configValue&stagemonitor.password=password. If the password is not set, dynamically changing the configuration is not available. The password can be omitted if set to an empty string.
```

I then fire up my client app and perform a remote call to the bean `com.mymodule.security.auth.server.LoginServiceBean` (which perform JDBC requests) and then look at my Kibana. I see that the indexes `[stagemonitor-metrics-]YYYY.MM.DD` and `[stagemonitor-requests-]YYYY.MM.DD` are available but only `[stagemonitor-metrics-]YYYY.MM.DD` contains data. To make matters worse, the data contains only the following fields: `@timestamp`, `_id`, `_index`, `score`, `_type`, and `measurement_type`. 

What am I missing in order to get complete monitoring from stagemonitor?

**Comment by felixbarny** [comment] 2016-06-06 17:16
Hi,

thanks for trying out stagemonitor.

How do you EJBs look like? Are they annotated with `@Remote`? I suspect that stagemonitor does not correctly pick up those. You could also try to annotate classes or methods you want to monitor with `@MonitorRequests`.

Are the metrics dashboards working (for example JVM)?

**Comment by domtoupin** [comment] 2016-06-06 17:37
Hi,

Yes, the EJB are annotated with `@Remote`; I will try to annotate the classes and methods we want to monitor. Unfortunately, we were hoping to be able to "inject" some monitoring in a production environment to monitor some servers task which we suspect to be too demanding.

I tried to find out how I could I could access the metrics dashboards but so far, I could not find any working URL (our application uses https and no Web servers are being used/configured). Aren't the metrics also sent to ElasticSearch?

**Comment by felixbarny** [comment] 2016-06-06 17:41
Do your EJBs also have a remote interface? The metrics dashboards are also in Kibana. Just go to the dashboard tab and search for JVM. It seems like you properly configured stagemonitor to send metrics to elasticsearch:

 ```
INFO  [org.stagemonitor.core.CorePlugin] (pool-9-thread-1) Sending metrics to Elasticsearch ([http://[my es url]:9200/]) every 60s
```

**Comment by domtoupin** [comment] 2016-06-06 17:47
Ah, I found the metric dashboard in Kibana, I was puzzled by the lack of data in the "Discover" tab and did not go any further.

As for our EJBs, they mostly have both a remote (`@Remote`) and local (`@Local`) interfaces.

**Comment by felixbarny** [comment] 2016-06-06 17:50
Ok. Please try the `@MonitorRequests` annotation so we can pinpoint the problem.

**Comment by domtoupin** [comment] 2016-06-06 18:28
I confirm that by adding the `@MonitorRequests`, the JDBC requests for that bean are indeed sent to ElasticSearch. It is unfortunate that the EJB are not picked up automatically since you must plan ahead what you want to monitor...

**Comment by felixbarny** [comment] 2016-06-06 18:35
Ok, that's great news. Now we know what the problem is. Actually, remote EJBs should be picked up automatically. Now we have to find out what's going wrong in that process. This is the class which detects remote EJBs: https://github.com/stagemonitor/stagemonitor/blob/master/stagemonitor-requestmonitor/src/main/java/org/stagemonitor/requestmonitor/ejb/RemoteEjbMonitorTransformer.java. And here is the test for it: https://github.com/stagemonitor/stagemonitor/blob/master/stagemonitor-requestmonitor/src/test/java/org/stagemonitor/requestmonitor/ejb/RemoteEjbMonitorTransformerTest.java

Can you spot anything that might be different for your EJBs? Can you paste one of your EJBs + the remote here? You can obviously delete the method bodies and alter the method names so you don't have to leak sensitive information.

**Comment by domtoupin** [comment] 2016-06-06 20:13
I think I finally figured out where the remote EJB stops short in our case. The way we designed our EJBs, we have one interface with all the methods common to remote and local interfaces, then we have two more interfaces, one annotated with `@Local` (in which we add all method specific to the local interface) and another one annotated with `@Remote` (in which we add all method specific to the remote interface). These two interfaces are then inherited by our bean implementation. We did not put the `@Remote` annotation in our bean implementation like you did in https://github.com/stagemonitor/stagemonitor/blob/master/stagemonitor-requestmonitor/src/test/java/org/stagemonitor/requestmonitor/ejb/RemoteEjbMonitorTransformerTest.java

Is there an easy way to visit the Bean hierarchy to find the `@Remote` annotation or should we move all of our annotation in our bean implementations?

By the way, thank you for everything you've been really, really helpful!

**Comment by felixbarny** [comment] 2016-06-07 05:29
That is totally possible! It would be great if you could contribute a test case for that in `RemoteEjbMonitorTransformerTest` as I don't quite get how your hierarchy looks like. I'll handle the implementation then. Do you think there are similar cases which should be considered? Do you know of any good documentation of the `@Remote` annotation and where it can be applied to?

I'm glad I could help :)

**Comment by domtoupin** [comment] 2016-06-07 12:00
The best documentation I could find for the `@Remote` annotation is the one from Oracle: http://docs.oracle.com/javaee/7/api/javax/ejb/Remote.html

Also, I created a minimal test case to reproduce our hierarchy but basically, it is exactly like yours except that the `@Remote` annotation is located on the interface rather than on the bean implementation and the annotation has no value.

I will try to submit a PR today with this test case.

**Comment by felixbarny** [comment] 2016-06-08 14:31
closed by 0662aa9c0dc2ba7d2fe6fd4e10ec5872c9583294

**Comment by domtoupin** [comment] 2016-06-10 13:43
I finally add a chance to test the new release (0.26.0) and now I get an error related to the class transformation:

```
09:29:29,489 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC000001: Failed to start service jboss.deployment.subunit."***.ear"."***.jar".INSTALL: org.jboss.msc.service.StartException in service jboss.deployment.subunit."***.ear"."***.jar".INSTALL: WFLYSRV0153: Failed to process phase INSTALL of subdeployment "***.jar" of deployment "***.ear"
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:154)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.VerifyError: Expecting a stackmap frame at branch target 38
Exception Details:
  Location:
    com/company/interfaces/remote/RemoteInterface$$$view1.getOptimizer(Ljava/util/List;)Lcom/company/Optimizer; @24: ifne
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 1294 04bd 0016 5903 2b53 12ab 1277 12ac
    0x0000010: 2ab8 009d 2ab4 0013 9a00 0e2a 2bb7 0041
    0x0000020: 4d01 4ea7 0027 2ab4 0019 2ab2 0046 04bd
    0x0000030: 0016 5903 2b53 b900 2704 00c0 0043 4d01
    0x0000040: 4ea7 0009 4e01 4da7 0003 2db8 00a1 2dc7
    0x0000050: 0005 2cb0 2dbf                         
  Exception Handler Table:
    bci [20, 68] => handler: 68
  Stackmap Table:
    same_frame(@20)
    same_locals_1_stack_item_frame(@68,Object[#146])
    append_frame(@74,Object[#67],Object[#146])
    same_frame(@78)
    same_frame(@84)

	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.jboss.invocation.proxy.AbstractProxyFactory.afterClassLoad(AbstractProxyFactory.java:95)
	at org.jboss.invocation.proxy.AbstractClassFactory.defineClass(AbstractClassFactory.java:166)
	at org.jboss.invocation.proxy.AbstractProxyFactory.getCachedMethods(AbstractProxyFactory.java:150)
	at org.jboss.as.ejb3.component.stateless.StatelessComponentDescription$3.configure(StatelessComponentDescription.java:150)
	at org.jboss.as.ee.component.DefaultComponentViewConfigurator.configure(DefaultComponentViewConfigurator.java:67)
	at org.jboss.as.ee.component.deployers.EEModuleConfigurationProcessor.deploy(EEModuleConfigurationProcessor.java:82)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	... 5 more
```

Do you want me to open another issue for this or should I reopen this one?
Do you have any idea what is going on?

**Comment by felixbarny** [comment] 2016-06-10 14:12
I think that this is most likely an error which is caused by byte buddy. @raphw do you know what's going on here?

**Comment by raphw** [comment] 2016-06-10 15:16
I will have a look, not supposed to happen. Is there an error reproduction that I can run? Can you point me to the advice class that is doing this instrumentation?

**Comment by felixbarny** [comment] 2016-06-10 15:44
@domtoupin: could you turn on this config https://github.com/stagemonitor/stagemonitor/wiki/Configuration-Options#debug-instrumentation. An try again? It won't fix the problem but turns byte buddy into debug mode. Hopefully this reveils the problem. Please post the relevant pieces of the logs then. 

@raphw This is the advice which is likely to cause the problem: https://github.com/stagemonitor/stagemonitor/blob/master/stagemonitor-requestmonitor/src/main/java/org/stagemonitor/requestmonitor/ejb/RemoteEjbMonitorTransformer.java
Unfortunately, I can't reproduce the problem. 

@domtoupin to confirm that that component is indeed the cause, could you please try to set `stagemonitor.instrument.excludedInstrumenter=RemoteEjbMonitorTransformer`

**Comment by domtoupin** [comment] 2016-06-10 17:08
Unfortunately, adding `stagemonitor.instrument.debug=true` doesn't add much relevant information (maybe something else is missing?):

```
INFO  [org.stagemonitor.core.instrument.AgentAttacher] (MSC service thread 1-8) Registering ExceptionMeteredTransformer
INFO  [org.stagemonitor.core.instrument.AgentAttacher] (MSC service thread 1-8) Registering TimedTransformer
INFO  [org.stagemonitor.core.instrument.AgentAttacher] (MSC service thread 1-8) Registering MeteredTransformer
INFO  [org.stagemonitor.core.instrument.AgentAttacher] (MSC service thread 1-8) Registering GaugeTransformer
INFO  [org.stagemonitor.core.instrument.AgentAttacher] (MSC service thread 1-8) Registering ProfilingTransformer
INFO  [org.stagemonitor.core.instrument.AgentAttacher] (MSC service thread 1-8) Excluding ElasticsearchSearchQueryTransformer
INFO  [org.stagemonitor.core.instrument.AgentAttacher] (MSC service thread 1-8) Registering MethodLevelMonitorRequestsTransformer
INFO  [org.stagemonitor.core.instrument.AgentAttacher] (MSC service thread 1-8) Registering ClassLevelMonitorRequestsTransformer
INFO  [org.stagemonitor.core.instrument.AgentAttacher] (MSC service thread 1-8) Registering RemoteEjbMonitorTransformer
INFO  [org.stagemonitor.core.instrument.ApplicationClassLoaderMatcher] (MSC service thread 1-8) Instrumenting ClassLoader ModuleClassLoader for Module "deployment-***.ear.***.jar".:main" from Service Module Loader: true
[...]
DEBUG [org.stagemonitor.core.instrument.StagemonitorByteBuddyTransformer] (MSC service thread 1-5) TRANSFORM com.company.beans.RemoteBean (RemoteEjbMonitorTransformer)
INFO  [org.stagemonitor.core.instrument.AgentAttacher] (MSC service thread 1-5) Installed agent in 546 ms
INFO  [org.stagemonitor.core.instrument.AgentAttacher] (MSC service thread 1-5) Attached agents in 545 ms
INFO  [org.stagemonitor.core.instrument.TimedElementMatcherDecorator] (MSC service thread 1-5) ElementMatcher TIME (nanoseconds total)
[...]
DEBUG [org.stagemonitor.core.instrument.StagemonitorByteBuddyTransformer] (MSC service thread 1-7) TRANSFORM com/company/interfaces/remote/RemoteInterface$$$view1 (RemoteEjbMonitorTransformer)
```

However, I confirm that by adding `stagemonitor.instrument.excludedInstrumenter=RemoteEjbMonitorTransformer` the problem goes away (as well as Remote EJB monitoring...)

**Comment by domtoupin** [comment] 2016-06-10 17:24
I don't know if this can be any help but here is the call stack we have when the line `DEBUG [org.stagemonitor.core.instrument.StagemonitorByteBuddyTransformer] (MSC service thread 1-7) TRANSFORM com/company/interfaces/remote/RemoteInterface$$$view1 (RemoteEjbMonitorTransformer)` is printed:

```
	RemoteEjbMonitorTransformer(StagemonitorByteBuddyTransformer).beforeTransformation(TypeDescription, ClassLoader) line: 166	
	StagemonitorByteBuddyTransformer$2.transform(Builder<?>, TypeDescription, ClassLoader) line: 103	
	AgentBuilder$Transformer$Compound.transform(Builder<?>, TypeDescription, ClassLoader) line: 1084	
	AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder$InitializationStrategy, ClassFileLocator, AgentBuilder$TypeStrategy, ByteBuddy, AgentBuilder$Default$NativeMethodStrategy, AgentBuilder$Default$BootstrapInjectionStrategy, AccessControlContext, AgentBuilder$Listener) line: 5282	
	AgentBuilder$Default$ExecutingTransformer$ByteBuddy$LoHOt9Zp(AgentBuilder$Default$ExecutingTransformer).transform(JavaModule, ClassLoader, String, Class<?>, ProtectionDomain, byte[]) line: 5689	
	AgentBuilder$Default$ExecutingTransformer$ByteBuddy$LoHOt9Zp(AgentBuilder$Default$ExecutingTransformer).transform(ClassLoader, String, Class<?>, ProtectionDomain, byte[]) line: 5630	
	TransformerManager.transform(ClassLoader, String, Class<?>, ProtectionDomain, byte[]) line: 188	
	InstrumentationImpl.transform(ClassLoader, String, Class<?>, ProtectionDomain, byte[], boolean) line: 428	
	ClassLoader.defineClass1(String, byte[], int, int, ProtectionDomain, String) line: not available [native method]	
	ModuleClassLoader(ClassLoader).defineClass(String, byte[], int, int, ProtectionDomain) line: 763	
	NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
	NativeMethodAccessorImpl.invoke(Object, Object[]) line: 62	
	DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43	
	Method.invoke(Object, Object...) line: 498	
	ClassFile.define(ClassLoader, ProtectionDomain) line: 281	
	ProxyFactory<T>(AbstractClassFactory<T>).defineClass() line: 164	
	ProxyFactory<T>(AbstractProxyFactory<T>).getCachedMethods() line: 150	
	StatelessComponentDescription$3.configure(DeploymentPhaseContext, ComponentConfiguration, ViewDescription, ViewConfiguration) line: 150	
	DefaultComponentViewConfigurator.configure(DeploymentPhaseContext, ComponentDescription, ComponentConfiguration) line: 67	
	EEModuleConfigurationProcessor.deploy(DeploymentPhaseContext) line: 82	
	DeploymentUnitPhaseService<T>.start(StartContext) line: 147	
	ServiceControllerImpl$StartTask.startService(Service<? extends S>, StartContext) line: 1948	
	ServiceControllerImpl$StartTask.run() line: 1881	
	ServiceContainerImpl$ContainerExecutor(ThreadPoolExecutor).runWorker(ThreadPoolExecutor$Worker) line: 1142	
	ThreadPoolExecutor$Worker.run() line: 617	
	ServiceContainerImpl$ServiceThread(Thread).run() line: 745	
```

Maybe is has something to do with the fact that this is a generated proxy class (`ProxyFactory<T>(AbstractClassFactory<T>).defineClass()`)?

**Comment by raphw** [comment] 2016-06-11 07:06
There is a good chance that Javassist generates code wothout stack-map-frames (within JBoss). Those frames are required by the verifier of the JVM. Byte Buddy by default reuses the information within a class as stack map frames are expensive to recompute.

Byte Buddy can ask ASM to recompute stack map frames nevertheless. On the Advice component, one can set the ClassWriter.COMPUTE_FRAMES option which is hower quite expensive. 

I would love a reproduction of this error, I could not recreate it using Byte Buddy and Wildfly.

**Comment by raphw** [comment] 2016-06-11 13:12
PPS: are there any other agents active? New Relic or Appdynamics etc?

**Comment by raphw** [comment] 2016-06-11 15:48
@felixbarny As a debugging help it would be great to a switch where the `onTransformer` method stores the generated class file (via `DynamicValue`) somewhere. This way, I could decompile the file and get the actual problem from the currupted class. Itherwise it is close to impossible to pinpoint the actual problem.

I assume that there is a problem related to how Javassist generates code vs. the way Byte Buddy generates code. I know that the named tools do not respect other Javaagents and cause problems by reading the original class file from the file system instead of reading the chained byte code provided by the transformer. The latter use of Javassist is my best guess so far.

**Comment by felixbarny** [comment] 2016-06-12 08:10
@raphw Good idea! I will add a config switch to export classes of a given name to the file system.

@domtoupin I  just noticed that the name of the corrupted class is `com/company/interfaces/remote/RemoteInterface$$$view1`. This is very strange, because stagemonitor does not instrument classes which contain `$$` as those are most likely generated classes. See https://github.com/stagemonitor/stagemonitor/wiki/Configuration-Options#exclude-containing. Did you change this option by chance?

**Comment by felixbarny** [comment] 2016-06-12 08:15
@raphw btw: Javassist does respect other agents, but only when using the `ByteArrayClassPath`. See https://github.com/stagemonitor/stagemonitor/commit/9a836b9a981ca94c8606c5985e04f6b0c61d5c9c#diff-23f1ac816755d08f19e279a2974ce7ecR216

**Comment by raphw** [comment] 2016-06-12 10:19
@felixbarny Ahh, this might just be. There is some strange behavior where the JVM does not validate certain (known) synthetic types but yields errors when the hash of the class file changed. I have really only seen it on WebSphere using J9, though.

PS: I know about this but many people do not so 99% of all Javassist agents make this error.

**Comment by felixbarny** [comment] 2016-06-12 10:34
@raphw what might just be?

@domtoupin I've added the config option which exports the generated classes. Could you try the [master](https://jitpack.io/#com.github.stagemonitor.stagemonitor/stagemonitor-web/master-SNAPSHOT) and add `stagemonitor.instrument.exportGeneratedClassesWithName=com.company.interfaces.remote.RemoteInterface$$$view1`? Then please attach the class file (the logs contain the exact location `Exported class modified by Byte Buddy: {}`) to this issue or mail it to me if you have doubts about posting it publicly. You can find my mail address in stagemonitor's [pom.xml](http://search.maven.org/#artifactdetails%7Corg.stagemonitor%7Cstagemonitor-web%7C0.26.0%7C).

**Comment by raphw** [comment] 2016-06-12 10:53
@felixbarny That  stagemonitor instrument a class that is not supposed to be instrumented and trigger a failed validation. By default, Byte Buddy does for example not instrument `synthetic` types to avoid some strange corner cases.

**Comment by domtoupin** [comment] 2016-06-13 12:14
Regarding your question whether I used `excludeContaining` in my `stagemonitor.properties` file, the answer is no.

Also, I will need to refer to my boss to make sure I can send you the `class` file and if there are no problems (I don't think there will be any) I will send it to you by email later today.

Thank you both for your help!

**Comment by felixbarny** [comment] 2016-06-13 12:44
Thx for sending me the class file. I've forwarded it to @raphw as well. It is very strange that this class is instrumented at all. Somehow it slips through the filter which excludes all classes containing `$$`. Could you try to set `stagemonitor.instrument.exclude=com.company.interfaces.remote.RemoteInterface$$$view1`? Maybe this works around the problem.

**Comment by domtoupin** [comment] 2016-06-13 19:53
I tried to use `stagemonitor.instrument.exclude=com.company.interfaces.remote.RemoteInterface$$$view1` but it seems there is more than just this one proxy which is failing (actually Wildfly deployment halt on the first exception). On the other hand, I believe I found something; in [RemoteEjbMonitorTransformer](https://github.com/stagemonitor/stagemonitor/blob/master/stagemonitor-requestmonitor/src/main/java/org/stagemonitor/requestmonitor/ejb/RemoteEjbMonitorTransformer.java) shouldn't the `or` parts be placed between parenthesis so that the `and` part (either `super.getIncludeTypeMatcher()` or `isPublic()`) applies for both `or` clauses?

In other words should those two methods
```
	@Override
	protected ElementMatcher.Junction<TypeDescription> getIncludeTypeMatcher() {
		return super.getIncludeTypeMatcher()
				.and(isAnnotatedWith(Remote.class))
				.or(implementsInterfaceWhichIsAnnotatedWithRemote());
	}

	@Override
	protected ElementMatcher.Junction<MethodDescription.InDefinedShape> getExtraMethodElementMatcher() {
		return isPublic()
				.and(overridesMethodFromRemoteAnnotationValue())
				.or(overridesMethodFromInterfaceWhichIsAnnotatedWithRemote());
	}
```
be rewritten thus?
```
	@Override
	protected ElementMatcher.Junction<TypeDescription> getIncludeTypeMatcher() {
		return super.getIncludeTypeMatcher()
				.and(isAnnotatedWith(Remote.class)
				     .or(implementsInterfaceWhichIsAnnotatedWithRemote()));
	}

	@Override
	protected ElementMatcher.Junction<MethodDescription.InDefinedShape> getExtraMethodElementMatcher() {
		return isPublic()
				.and(overridesMethodFromRemoteAnnotationValue()
				     .or(overridesMethodFromInterfaceWhichIsAnnotatedWithRemote()));
	}
```

It seems to do the trick on my end but I don't know if it would break anything...

**Comment by felixbarny** [comment] 2016-06-14 06:54
Oh my gosh, I think you are right. Good catch!

**Closed** 2016-06-14 07:33 UTC

**Comment by felixbarny** [comment] 2016-06-14 08:06
I've just did a bugfix release: https://github.com/stagemonitor/stagemonitor/releases/tag/0.26.1

@raphw due to a bug, a generated class slipped through and was instrumented. But I think it would be still interesting to know why this leads to a verify error, but there is no hurry. Thanks for your help :)

**Comment by domtoupin** [comment] 2016-06-14 11:42
Thank you for everything, it now works as expected!

**Comment by felixbarny** [comment] 2016-06-14 11:44
Great to hear :)

If there is anything else that doesn't quite work as expected or if something in the docs is unclear, don't hesitate to create another issue.

**Comment by raphw** [comment] 2016-06-15 14:52
I now investigated the class file but it seems to be a different class than that for which the error is reported. Could you send me the correct file (`com/company/interfaces/remote/RemoteInterface$$$view1`, I received `com.netappsid.erp.server.services.interfaces.remote.OptimizerServicesRemote$$$view27786875817042659830` that does not contain a `getOptimizer` method. This way, I do not know what section of the class file to investigate.)

I have just recently fixed another bug which might be related. I am cleaning up tomorrow and will release a new version of Byte Buddy afterwards.

Could you do me a favour and try to explicitly instrument these files with the new version of Byte Buddy even Stagemonitor new excludes them? I would like to fix the root cause of this problem in case that there is a mistake in the code generation which could also affect other classes.

**Comment by felixbarny** [comment] 2016-06-15 14:58
@domtoupin: the easiest way to do so is to downgrade to stagemonitor 0.26.0 again and add an explicit dependency to byte-buddy 1.4.1: http://mvnrepository.com/artifact/net.bytebuddy/byte-buddy/1.4.1

**Comment by raphw** [comment] 2016-06-15 15:00
@domtoupin It is fixed in version 1.4.2 which is not yet released. I still have to change some rough edges. Also, Byte Buddy 1.4.* has some minor API changes. Did Stagemonitor 0.26.0 already depend on an 1.4.* version?

**Comment by felixbarny** [comment] 2016-06-15 15:07
> Byte Buddy 1.4.* has some minor API changes. Did Stagemonitor 0.26.0 already depend on an 1.4.* version?

Yes. So what is the easiest way to test against the byte-buddy master? Use something like JitPack?

**Comment by domtoupin** [comment] 2016-06-15 16:15
@raphw You did receive the right file; I was just editing path name and method name to anonymize them. The actual method name is `getOptimizerFromProductionBatch`

I will try to build a 1.4.2-snapshot version of bytebuddy as soon as I have some time and use it to build a "new" stagemonitor 0.26.0 to see if the problem is still there.

**Comment by raphw** [comment] 2016-06-15 16:19
@domtoupin Thank you, perfect. Make sure to check out the `development` branch!

I will have another look at the file.

**Comment by raphw** [comment] 2016-06-16 08:10
1.4.2 is now released and available in Maven Central. I would still appreciate if you could run the test and give me feedback. Thank you!

**Comment by domtoupin** [comment] 2016-06-20 19:13
@raphw I did ran the test and unfortunately I came across almost exactly the same error, the only notable difference being the "branch target" number being now "35" in place of the previous "38". Please let me know if there are any other tests you would like me to perform.

However, note that as this is no longer a blocking issue, I will only perform those tests when I got some spare time.

**Comment by raphw** [comment] 2016-06-20 21:45
@domtoupin Hmm, this sucks and is very strange. Could you once again extract the class file and send it to me to rafael (dot) wth (at) gmail (dot) com? I am using the component in production at quite a lot of places now and never encountered the error what makes me wonder?
