### ISSUE TITLE
stagemonitor.property.overrides allow external filesystem property file

### ISSUE THREAD

**Issue by zucher** [stagemonitor/stagemonitor#61] opened 2015-03-18 20:31 UTC
Hello,

Currently the PropertyFileConfigurationSource file is restrict to callpath location for stagemonitor.properties file.

Could you support as failover of getResourceAsStream() request an alternative file open on filesystem searching.

Regards

zucher

**Comment by felixbarny** [comment] 2015-03-19 06:56
Duplicate of #62

**Closed by felixbarny** 2015-03-19 06:56 UTC
Labels: duplicate
