### ISSUE TITLE
JDBC monitoring with DruidDataSource

### ISSUE THREAD

**Issue by TimYi** [stagemonitor/stagemonitor#201] opened 2016-09-19 03:16 UTC
Hi, I'm a Chinese user. Connection pool druid is very famous in China, it's alibaba's opensource project.
Could you add com.alibaba.druid.pool.DruidDataSource to dataSource.implementations as a default?
Druid's project address: https://github.com/alibaba/druid

**Comment by felixbarny** [comment] 2016-09-19 13:25
Unfortunately, it's not as easy as that. The problem is that `com.alibaba.druid.pool.DruidDataSource#getConnection()` does not return `java.sql.Connection` but a custom subtype (`com.alibaba.druid.pool.DruidPooledConnection`).

Stagemonitor uses byte code manipulation to wrap the connection. See [DefaultConnectionMonitoringTransformer](https://github.com/stagemonitor/stagemonitor/blob/master/stagemonitor-jdbc/src/main/java/org/stagemonitor/jdbc/DefaultConnectionMonitoringTransformer.java). But that can only work if the return type is `java.sql.Connection` and not a subtype.

**Comment by TimYi** [comment] 2016-09-20 05:33
@felixbarny 
I look into the code, generally understand what's your concern. I add DruidDataSource to dataSource.implementations, but it not works, now I know why.
From object orient design point of view,` DruidDataSource#getConnection()` returns subclass of super class has noting wrong. I'm not familiar with byte code manipulation, maybe manipulate with any subclass may destroy their extended functions?

**Comment by felixbarny** [comment] 2016-09-20 08:43
> From Object-Oriented point of view,DruidDataSource#getConnection() returns a subclass has noting wrong.

That is totally true, but this prevents me from modifying the `DruidDataSource#getConnection()` method to return a wrapped connection (see `DefaultConnectionMonitoringTransformer#monitorGetConnection` and `ConnectionMonitor#monitorGetConnection`) as returning a superclass (`java.sql.Connection`) of the declared return type `DruidPooledConnection` is not possible.

However, when p6spy 3 is released, I have an idea for implementing another possibility for JDBC monitoring without byte code maipulation. However, you will have to configure p6spy manually like explained here: http://p6spy.readthedocs.io/en/latest/install.html

**Comment by felixbarny** [comment] 2016-09-22 14:50
I've implemented my idea. Could you try it out to see if it works for you? You'll have to build stagemonitor manually:

```bash
git clone https://github.com/stagemonitor/stagemonitor.git
cd stagemonitor
git checkout p6spy3
./gradlew install
```

Then set the stagemonitor version to `0.29.0-SNAPSHOT` in your `pom.xml` or `build.gradle` file.

As already explained in the comment above, you then have to configure p6spy: http://p6spy.readthedocs.io/en/latest/install.html.

You may also want to create a spy.properties file inside your classpath (`src/main/resources/spy.properties`) with the following content:

```properties
modulelist=
```

This prevents the creation of a `spy.log` file which contains information about executed sql statements.

**Comment by TimYi** [comment] 2016-09-23 01:47
Ok, I'll try it soon, thank you for your concern.

**Comment by TimYi** [comment] 2016-09-27 08:54
@felixbarny I tried it out, there's something to improve but it finally works.
I checkout p6spy3 branch, install, Then config p6spy.
At first I started my application, It runs into error:
`Caused by: java.lang.IllegalStateException: dbType not support : null, url jdbc:p6spy:mysql://localhost:3306/mfront?useUnicode=true&characterEncoding=UTF-8`
Druid has a wall plugin,  it can't recognize p6spy driver connection url. Then I remove this plugin.
Another error occurs:
```
java.sql.SQLException: Unable to find a driver that accepts jdbc:mysql://localhost:3306/mfront?useUnicode=true&characterEncoding=UTF-8
	at com.p6spy.engine.spy.P6SpyDriver.findPassthru(P6SpyDriver.java:115)
```
I'v put my spy.properties under every possible tomcat classpath, etc $CATLINA_HOME/lib, WEB-INF/classes. And set `driverlist=com.mysql.jdbc.Driver` . But it doesn't work.
At last, I write a `ServletContextListener` and regist mysql driver manually:
`DriverManager.registerDriver(new com.mysql.jdbc.Driver());`
Then it starts, and I see sql log in kibana discover page.
I think spy.properties file does not work under tomcat environment. I can't find out where p6spy load this config file.

**Comment by felixbarny** [comment] 2016-09-27 09:02
Yes, there was a bug in p6spy! The driver list issue is resolved in the current p6spy master: https://github.com/p6spy/p6spy/pull/350.

So when p6spy 3 final is released, `driverlist=com.mysql.jdbc.Driver` should work.

I'll leave this issue open until p6spy3 is merged into stagemonitor master.

**Comment by TimYi** [comment] 2016-09-27 09:36
Thank you, felixbarny. Stagemonitor is really a cool tool. It's so seamless and powerful. Our application have been optimized a lot since we can find where slows down by the help of Stagemonitor.

**Comment by felixbarny** [comment] 2016-09-27 09:38
That's great to hear, appreciate it a lot :)

**Closed** 2016-10-28 08:11 UTC
