### ISSUE TITLE
JDBC Monitoring not work as expected

### ISSUE THREAD

**Issue by torobcheh** [stagemonitor/stagemonitor#143] opened 2016-04-08 08:28 UTC
I build rest services which are deployed in a WildFly and i want to monitor the JDBC-Calls. I use CXF as JAX-RS implementation, Spring, Spring Data JPA and Hibernate and Hikari as CP
When i use Kibana i expect 
1.) that there is a field in the index where the sql statement is stored - but see it only as part of the callStack 
![image](https://cloud.githubusercontent.com/assets/18343844/14377891/8deae48c-fd72-11e5-9224-2647c788b1c2.png)

2.) when is look at the JDCB Dashboard i expect that i could see my queries, but all are aggregated under "CXFNonSpringServlet#invoke"
![image](https://cloud.githubusercontent.com/assets/18343844/14377553/8b63e792-fd70-11e5-9fcd-fe73735035a4.png)

By the way -  have used javamelody before, but our idea to integrate elasticsearch is great

**Comment by felixbarny** [comment] 2016-04-08 08:38
Sql statements are only stored inside the call tree. As there can be multiple sql statements per requests one field to store the sql would not be enough. Why do you need an extra field for the statements?

The SQL statements are always aggregated under the parent's method name. This is usually a DAO method. Do you have a suggestion for a different aggregation name?

**Comment by torobcheh** [comment] 2016-04-08 12:49
1.) Was only a question, cause when the sql statement is stored in a single  field it may be easier to select requests with a specific statement, like in JavaMelody

2.) I have a Interface and a Implementation for Rest, and the Rest application is defined in a Spring context file with the help of CXF. a service layer and the Spring Data Interface (Repository) with methods and query anntotations. So why are the Sql's are not aggregated on repository level

@Transactional(readOnly = true)
public interface MapDataTypeRepository extends JpaRepository<MapDataType, Integer>
{
_  @Query("SELECT mdt FROM MapDataType mdt WHERE mdt.type = :" + EnumerationConstants.TYPE + " ORDER BY mdt.sortKey, mdt.term")_
  public List<MapDataType> **findListOfMDTByType**(@Param(EnumerationConstants.TYPE) String type);

**Comment by felixbarny** [comment] 2016-04-08 12:58
Could you send me a link to this Javamelody feature?

I did not yet test with Spring Data repository interfaces. Chances are that this does not currently work. What is your setting for `stagemonitor.instrument.include`? In which package is your MapDataTypeRepository?

**Comment by ryanrupp** [comment] 2016-04-08 14:04
About capturing SQL statements, in addition to Stagemonitor I've been using Elastic's Packetbeat (https://www.elastic.co/products/beats/packetbeat) which can capture MySQL and PostgreSQL network traffic. This tracks each document as an individual SQL statement so the query text is indexed/searchable. I usually start investigating issues with Stagemonitor and then dig into the details of the SQL with the packetbeat captured data. Stagemonitor could have a separate index for only SQL that is indexed but maybe that's overkill/too redundant although it would allow me to not have to capture the data via packetbeat then maybe. Main thing is the call stack field is too big to be indexed.

I'm also using Spring data JPA with Wildfly and the repository methods don't get picked up in the callstack. The reason I think it's happening for me though is the way have our application packaged where we deploy an EAR with the JPA/service layer as top level libraries in the EAR then also a WAR which contains stagemonitor/Spring MVC code. I figured it had to do something with classloader/module separation but I haven't had a chance to investigate this.

**Comment by felixbarny** [comment] 2016-04-08 14:08
This would totally be possible. But I'd like to hear more about the use case. Why and when are you searching for particular SQL statements?

Maybe the reason that the interfaces are not picked up is that spring implements the class at runtime and that the instrumenter can't hook in because of that.

**Comment by torobcheh** [comment] 2016-04-11 07:24
using stagemonitor.instrument.include was the missing link :+1:

**Comment by torobcheh** [comment] 2016-04-11 07:55
but .. the sql's are doubled in the stack log
my own sql log
09:50:55,840 INFO  [stdout] (default task-20) Hibernate: select mapdatatyp0_.MANDATOR_SPECIFIC as col_0_0_ from MAP_DATA_TYPES_HEAD mapdatatyp0_ where mapdatatyp0_.TYPE=?

09:50:55,875 INFO  [stdout] (default task-20) Hibernate: select mapdatatyp0_.LANGID as LANGID1_0_,  ......
 from MAP_DATA_TYPES mapdatatyp0_ where mapdatatyp0_.TYPE=? order by mapdatatyp0_.SORT_KEY, mapdatatyp0_.TERM

and the stack from stagemonitor
![image](https://cloud.githubusercontent.com/assets/18343844/14420279/8273bb0a-ffcb-11e5-9a27-8cbcb360db21.png)

**Comment by felixbarny** [comment] 2016-04-11 15:12
Hm, that indeed looks very strange. Any chance you can reproduce this in a simple example application you can hand me over?

**Comment by felixbarny** [comment] 2016-04-15 11:09
Are you deploying multiple applications to WildFly?

**Comment by mpeter** [comment] 2016-04-20 03:24
I am seeing the duplicated SQL statements as well, and yes, I am deploying multiple .war files to the same application server -- is there anything behind your question that I could modify in order to prevent the duplicates?

**Comment by felixbarny** [comment] 2016-04-20 05:23
Do you also get duplicates when deploying only one application? If not, this should be fixed in the upcoming version which ist powered by Byte Buddy instead of Javassist.

**Comment by torobcheh** [comment] 2016-04-20 10:24
sorry answering so late - the direction is right - when i deploy only a single application with enabled stagemonitor the sql statements only logged once

**Closed** 2016-04-20 13:39 UTC
Labels: state: in-progress

**Comment by mpeter** [comment] 2016-04-20 17:14
+1 !

**Comment by torobcheh** [comment] 2016-04-20 17:32
thank you :+1:

**Comment by felixbarny** [comment] 2016-04-20 20:13
You are very welcome! Have you guys already tried it out? See the readme.md on how to get the lastest snapshot from master. I'd really appreciate your feedback. If all is working well I'll release the new version soon.
