### ISSUE TITLE
Will the ehcache plugin support ehcache 3?

### ISSUE THREAD

**Issue by mahanhz** [stagemonitor/stagemonitor#232] opened 2017-01-03 17:44 UTC
The current ehcache plugin doesn't work with version 3.
Will that be supported in the near future?

**Comment by felixbarny** [comment] 2017-02-02 08:49
Sorry for not responding. This is a duplicate of #93. I'm currently busy implementing distributed tracing support. So this will have to wait a little longer once more. Unless someone wants to help with the implementation.

**Closed by felixbarny** 2017-02-02 08:49 UTC
